### ISSUE TITLE
Installing nix-alien

### ISSUE THREAD

**Issue by koppor** [thiagokokada/nix-alien#104]
I am following the [installation guide of nix-alien](https://github.com/thiagokokada/nix-alien#nixos-installation).

This complains

    error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument

Thus, I set the sha256 sum:

```

{ ... }:

let
  nix-alien-pkgs = import (
    builtins.fetchTarball {
      url = "https://github.com/thiagokokada/nix-alien/tarball/master";
      sha256 = "1pibz7la81s9ijyq7m3zv830waw1k6km227gab580086kl8kcpmm";
    }
  ) { };
in
{
  environment.systemPackages = with nix-alien-pkgs; [
    nix-alien
  ];

  # Optional, but this is needed for `nix-alien-ld` command
  programs.nix-ld.enable = true;
}
```

Then, however, I get

    error: 'builtins.storePath' is not allowed in pure evaluation mode

Which I am unable to solve.

---

Can the installation guide be refined to guide noobs? :innocent:

**Comment by thiagokokada** [comment]
Are you using Flakes? If yes, you should follow the Flakes guide: https://github.com/thiagokokada/nix-alien#nixos-installation-with-flakes

> Can the installation guide be refined to guide noobs? 😇

PRs are definitely welcome.

**Comment by koppor** [comment]
OK, I'll close the issue. I am experimenting where to put the content of the link. I think, the how-to at https://nixos-and-flakes.thiscute.world/nixos-with-flakes/modularize-the-configuration guides me to the correct location.

**Comment by koppor** [comment]
To ease googling for others, I posted a follow-up question at https://www.reddit.com/r/NixOS/comments/19ebm60/how_to_install_nixalien_when_using_flake/?utm_source=share&utm_medium=web2x&context=3.

**Comment by pianocomposer321** [comment]
For those who landed here who may be wondering how to get this working without using flakes, the solution is to use the `--impure` flag when rebuilding your nixos-config:

```
$ sudo nixos-rebuild switch --impure
```
