### ISSUE TITLE
No usable options for libSkiaSharp.so

### ISSUE THREAD

**Issue by ParetoOptimalDev** [thiagokokada/nix-alien#15]
Trying to run nix-alien on [talon voice](https://talonvoice.com/dl/latest/talon-linux.tar.xz) fails because no good options can be found for `libSkiaSharp.so`.

Here are the options presented:

```
  jellyfin.out                                                                    mission-planner.out                                                             alttpr-opentracker.out                                                        > wasabiwallet.out   
'libSkiaSharp.so'> 
```

And here is the attempt to run:

```
[nix-shell:~/system]$ nix run "github:thiagokokada/nix-alien#nix-alien" --  --recreate /home/nixos/Downloads/talon/talon
Selected candidate for 'libQt5Widgets.so.5': libsForQt514.full.out
Selected candidate for 'libpython3.9.so.1.0': python39Full.out
Selected candidate for 'libusb-1.0.so.0': libusb1.out
Selected candidate for 'libSkiaSharp.so': wasabiwallet.out
No candidate found for 'libw2ldecode.so'
Selected candidate for 'libw2ldecode.so': None
Selected candidate for 'libQt5DBus.so.5': libsForQt514.full.out
Selected candidate for 'libQt5X11Extras.so.5': libsForQt514.full.out
Selected candidate for 'libGL.so.1': xorg_sys_opengl.out
Selected candidate for 'libQt5Gui.so.5': libsForQt514.full.out
Selected candidate for 'libQt5Core.so.5': libsForQt514.full.out
Selected candidate for 'libstdc++.so.6': gcc-unwrapped.lib
File '/home/nixos/.cache/nix-alien/7d515bd9-aa23-5d9a-a57a-86c6b77690fb/fhs-env/default.nix' created successfuly!
/home/nixos/Downloads/talon/talon: error while loading shared libraries: libSkiaSharp.so: cannot open shared object file: No such file or directory
```

**NOTE**: I tried each available option presented for `libSkiaSharp.so`, not just the one above.

I'm unsure of how to proceed here. Given this library is aimed at newer users just trying to get binaries to run, I figured this issue might be appropriate.

One potential resolution being a section added to the readme of what to do in this situation.

Thanks!

**Comment by thiagokokada** [comment]
About `libw2ldecode.so`: well, this can happen, it is not guarantee that every library will be available on nixpkgs. If you know that the package exists with its name, you can pass `--additional-package` as described in [Limitations](https://github.com/thiagokokada/nix-alien#limitations).

About `libSkiaSharp.so`, what probably happened is that all packages that `nix-index` picked were a package that embedded its own copy of `libSkiaSharp.so`, not the library itself. This generally will not work, and you generally should select the library own package (that may or may not exist). It is kinda impossible to differentiate between a package that is a library vs a package that is just embedding its own copy of some libraries, so this confusion may happen.

> I'm unsure of how to proceed here. Given this library is aimed at newer users just trying to get binaries to run, I figured this issue might be appropriate.

Probably the most sure way would be to package talon on nixpkgs, even if it isn't necessary easy. `nix-alien` always meant to be a quick and dirty hack that tries to work in some cases, but it does have its limitations.

Another option if you want to play a little more is to open `/home/nixos/.cache/nix-alien/7d515bd9-aa23-5d9a-a57a-86c6b77690fb/fhs-env/default.nix` file and try to play it yourself, maybe adding some libraries that seems to help for your particular case. Afterwards, running `nix-alien /home/nixos/Downloads/talon/talon` should use your edited `default.nix` file.

**Comment by thiagokokada** [comment]
In [5b056bf](https://github.com/thiagokokada/nix-alien/commit/5b056bf4a8f1b29deab2ebc8fc2e9dd95a6a1000) I improved the filtering so it should reduce the number of false positives located by `nix-alien`.

It means that probably you will see way less results, however for the good part the chances of they working are higher.

About the missing libraries: we really can't do much if the library is not available in `nixpkgs`. You can always package the missing library yourself, or create an issue so hopefully someone can package the library for you. Considering this, I am closing this issue.
