### ISSUE TITLE
How does this compare to steam-run?

### ISSUE THREAD

**Issue by danbst** [thiagokokada/nix-alien#24]
`steam-run` is a Nixpkgs tool for running Steam games unpatched, but can be used to run all other Linux programs unpatched. How does `nix-alien` compare to that?

This is a question, but the answer would be great to add to documentation.

**Comment by thiagokokada** [comment]
`steam-run` has a set of included packages. This is both a pro and a con: it means that a good amount of random programs may run under it, but it the `steam-run` FHS env is missing some dependency for your program, it will not run. Also, maybe you want to run a program with one or two dependencies only, while `steam-run` would force you to get a huge amount of packages just to run this program.

`nix-alien` will analyze the binary to get its dependencies, so the generated FHS env will be as minimal as possible. It will also generate a Nix file under the `$XDG_CACHE_HOME/nix-alien` directory, that it means you can use it as a base for creating a proper derivation.
