### ISSUE TITLE
README: `nixosModules.nix-ld` is not an overlay

### ISSUE THREAD

**Issue by lourkeur** [thiagokokada/nix-alien#25]
At line 201 in the [nixos-installation-with-flakes](https://github.com/thiagokokada/nix-alien#nixos-installation-with-flakes) section, the `nix-ld` module is put in `nixpkgs.overlays`. This didn't work on my machine, it should probably be an import.

**Comment by thiagokokada** [comment]
You are right. Can you open a PR?
