### ISSUE TITLE
test_create_fhs_env_drv_flake fails on aarch64-linux

### ISSUE THREAD

**Issue by LegitMagic** [thiagokokada/nix-alien#30]
Since the flake generated by the test test_create_fhs_env_drv_flake gives an output with `system = "x86_64-linux`, which of course fails on an aarch64 machine. Using `aarch64-linux` in the test works results in nix-alien's tests passing and nix-alien works perfectly fine.

**Comment by thiagokokada** [comment]
PRs are welcome, I have zero ways to test `aarch64-linux`.

**Comment by thiagokokada** [comment]
Hope with https://github.com/thiagokokada/nix-alien/pull/32 it fixes this issue, since I don't explicitly pass the value of `system` anymore (instead, I derivate it from `pkgs`).

**Comment by thiagokokada** [comment]
> Since the flake generated by the test test_create_fhs_env_drv_flake gives an output with system = "x86_64-linux, which of course fails on an aarch64 machine.

I did take a look at the test and it looks correct to me, because even if I explicitly compare with `x86_64-linux`  I also mock the value of the return function, so it should have worked (maybe the mock itself failed?).

Anyway, going to take a look at this later. Maybe there is a better way to check for this.

**Comment by thiagokokada** [comment]
Found the issue, the problem was that I was mocking the wrong namespace: https://github.com/thiagokokada/nix-alien/commit/6a630972faef65980d84602babe92d46ce499957

**Comment by LegitMagic** [comment]
Fix seems to work, thanks!

**Comment by thiagokokada** [comment]
Just setting up a CI in `aarch64-linux` with #38.

Hope this ensure that this kinda of issue doesn't happen in future.
