### ISSUE TITLE
Error building on nixos-unstable

### ISSUE THREAD

**Issue by JCapucho** [thiagokokada/nix-alien#33]
Hi, I'm currently using `nix-alien` in my system derivation and I've recently updated `nixpkgs` to `7e52b35fe98481a279d89f9c145f8076d049d2b9`, this broke my derivation build with the error:

```
error: 'nixFlakes' has been renamed to/replaced by 'nixVersions.stable'
```

I've traced it back to `nix-alien` which uses the now deprecated `nixFlakes` and removing `nix-alien` from the derivation does fix the build.

**Comment by thiagokokada** [comment]
Closed by [8da508a](https://github.com/thiagokokada/nix-alien/commit/8da508a542f258b8f37df18580144e344beab4c4).
