### ISSUE TITLE
Bad example in README

### ISSUE THREAD

**Issue by hissssst** [thiagokokada/nix-alien#35]
It turns out that overlays in flakes use main `nixpkgs` input, but not the `nix-alien`'s `nixpkgs`

So this example
```nix
          nixpkgs.overlays = [
            self.inputs.nix-alien.overlays.default
          ];
```

Is incorrect and leads to #34 even if without `inputs.nixpkgs.follows = "nixpkgs";`

**Comment by thiagokokada** [comment]
> It turns out that overlays in flakes use main `nixpkgs` input, but not the `nix-alien`'s `nixpkgs`
> 
> So this example
> 
> ```nix
>           nixpkgs.overlays = [
>             self.inputs.nix-alien.overlays.default
>           ];
> ```
> 
> Is incorrect and leads to #34 even if without `inputs.nixpkgs.follows = "nixpkgs";`

This is correct and how a overlay should work. If you want to use the nixpkgs pin you need to use the packages instead of overlay.

And yeah, this is not documented. But PRs are welcome!

**Comment by thiagokokada** [comment]
Fixed in commit: https://github.com/thiagokokada/nix-alien/commit/221f89a945cd7e345d9fe7362741100ec9c05d82.
