### ISSUE TITLE
can't install nix-alien with flak

### ISSUE THREAD

**Issue by xBLACKICEx** [thiagokokada/nix-alien#48]
my flack is build success but can't install nix-alien and nix-alien-xx etc...
![Screenshot_20221114_200853](https://user-images.githubusercontent.com/51036094/201746178-2344eae0-1d24-4649-ae52-88f476f1ae36.png)
with cmd : fd "nix-alien" only get :
![Screenshot_20221114_201703](https://user-images.githubusercontent.com/51036094/201746670-e2912a45-cf22-40fa-a081-e4ca451fcacd.png)

my flake.nix
```nix
{
  description = "NixOS Configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    nix-alien.url = "github:thiagokokada/nix-alien";
    nix-ld = {
      url = "github:Mic92/nix-ld";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@ { self, nixpkgs, nix-alien, home-manager,hyprland, dedsec-grub-theme, ... }:
    let
      users = {
        username = {
          name = "username";
        };
      };
    in
    {
      nixosConfigurations = (
        import ./NixOS-Hosts {
          inherit (nixpkgs) lib;
          inherit inputs self nixpkgs nix-alien home-manager hyprland dedsec-grub-theme users; # Also inherit home-manager so it does not need to be defined here.
        }
      );
    };
}
``` 

my NixOS-Hosts/default.nix
```nix
{ self, lib, inputs, nixpkgs, nix-alien, home-manager, hyprland, dedsec-grub-theme, users, ... }:

let
  system = "x86_64-linux";                                  # System architecture
  pkgs = import nixpkgs {
    inherit system;
    config.allowUnfree = true;                              # Allow proprietary software
  };
  lib = nixpkgs.lib;
in
{
    laptop = lib.nixosSystem {                                # Laptop profile
    inherit system pkgs;
    specialArgs = { inherit inputs users self system; };
    modules = [
      hyprland.nixosModules.default
      dedsec-grub-theme.nixosModule
      ({ self, system, ... }: {
            imports = [
              # Optional, but this is needed for `nix-alien-ld` command
              self.inputs.nix-ld.nixosModules.nix-ld
            ];
            environment.systemPackages = with pkgs; with self.inputs.nix-alien.packages.${system}; [
              nix-alien
              nix-index # not necessary, but recommended
              nix-index-update
            ];
      })
      ./Laptop
    ];
  };
}
```

**Comment by thiagokokada** [comment]
Without the errors, I don't know what the problem is.

Or do the build works, but the problem is you not adding the `nix-alien` in the `environment.systemPackages` or something similar?

See the docs: https://github.com/thiagokokada/nix-alien#nixos-installation-with-flakes

**Comment by xBLACKICEx** [comment]
> Without the errors, I don't know what the problem is.
> 
> Or do the build works, but the problem is you not adding the `nix-alien` in the `environment.systemPackages` or something similar?
> 
> See the docs: https://github.com/thiagokokada/nix-alien#nixos-installation-with-flakes

Sorry I don't know why I posted it without finishing it, I guess it's because of the wrong carriage return.

**Comment by souxd** [comment]
I'm having a similar issue: from what i saw i'm not doing anything wrong but nix-alien wont be installed... I cant call any of nix-alien or nix-ld

my flake: 
https://pastebin.com/TcSfbsYF

**Comment by souxd** [comment]
I'm not sure why it wasn't working before (if you know why please tell me) but today i decided to organize my flake and it's working just fine now

flake output:
https://github.com/souxd/nixos-config/blob/master/outputs/nixos-conf.nix

**Comment by KenMacD** [comment]
I suspect what's commonly happening here is that `nix-alien` is already in the scope which results in the  `with self.inputs.nix-alien.packages.${system};` not actually doing anything. Then instead of having the `nix-alien` packge in the `systemPackages` you end up with the module instead.

At least that's what happened to me when I had my `specialArgs` set to `inputs`. Perhaps the `README.md` could remove the with and prefix both packages (or set some other key in a `let`)?

**Comment by xBLACKICEx** [comment]
i re try again now is work for me i don't very know why. here is the code.

flake.nix
```nix
# This can be built with nixos-rebuild --flake .#myhost build
{
  description = "NixOS Configuration";

  inputs = {
    nix-alien.url = "github:thiagokokada/nix-alien";
    nix-ld = {
      url = "github:Mic92/nix-ld";
      # build with your own instance of nixpkgs
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@ { self, nixpkgs, nix-ld,  ... }:
    let
      users = {
        username = {
          name = "username";
        };
      };
    in
    {
      nixosConfigurations = (
        import ./NixOS-Hosts {
          inherit (nixpkgs) lib;
          inherit inputs nix-ld nixpkgs nix-alien home-manager hyprland dedsec-grub-theme users; # Also inherit home-manager so it does not need to be defined here.
        }
      );
    };
}
```

hosts.nix
```nix
{ lib, inputs, nix-ld, nix-alien, nixpkgs, home-manager, hyprland, dedsec-grub-theme, users, ... }:

let
  system = "x86_64-linux";                                  # System architecture
  pkgs = import nixpkgs {
    inherit system;
    config.allowUnfree = true;                              # Allow proprietary software
  };
  alien-pkgs = inputs.nix-alien.packages.${system};
  lib = nixpkgs.lib;
in
{
    laptop = lib.nixosSystem {                                # Laptop profile
    inherit system pkgs ;
    specialArgs = { inherit inputs alien-pkgs users; };
    modules = [
      nix-ld.nixosModules.nix-ld
      hyprland.nixosModules.default
      dedsec-grub-theme.nixosModule
      ./Laptop
    ];
  };
}
```

system.nix
```nix
{ config, pkgs, inputs, alien-pkgs, lib, ... }:
{
  environment.systemPackages = with pkgs; with alien-pkgs; [
      nix-alien
      nix-index # not necessary, but recommended
      nix-index-update
  ]
}
