### ISSUE TITLE
Issue with spaces in filenames

### ISSUE THREAD

**Issue by hissssst** [thiagokokada/nix-alien#71]
This time it's not in python-ldd, but in fhs-init script
File: `/nix/store/m06n0mbah9ymf4970rmvwlgdjrawpw55-dota2-fhs-init`

```bash
#!/nix/store/rnkas52f8868g1hjdlldbvh6snm3pglv-bash-5.2-p15/bin/bash
source /etc/profile
cat > /etc/ld.so.conf <<EOF
/lib
/lib/x86_64-linux-gnu
/lib64
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib64
/lib/i386-linux-gnu
/lib32
/usr/lib/i386-linux-gnu
/usr/lib32
/run/opengl-driver/lib
/run/opengl-driver-32/lib
EOF
ldconfig &> /dev/null

exec /path/to/file with spaces "$@"
```

**Comment by thiagokokada** [comment]
Can you give more details? So the issue is that `nix-alien-ld` does work with filename with spaces, but `nix-alien` does not?

**Comment by thiagokokada** [comment]
Ok, I did a quick check and it seems to be an issue with `buildFHSUserEnv` somewhere.

I don't really have time right now to track what is the issue though, so you either can report this upstream or wait until I have more time to investigate it further (and to be clear, this is not a high priority thing to me right now).

For now, the workaround is to just rename the binaries and it should work.

**Comment by hissssst** [comment]
What upstream are you talking about? nixos/nixpkgs?

**Comment by thiagokokada** [comment]
> What upstream are you talking about? nixos/nixpkgs?

Yes.

**Comment by Atemu** [comment]
nix-alien needs to escape the binary's path. I've updated the docs to mention this in https://github.com/NixOS/nixpkgs/pull/233209.

**Comment by thiagokokada** [comment]
Pushed https://github.com/thiagokokada/nix-alien/commit/936c78f734260784b8df29535e7ef83fa9563fd7 that should fix this issue. Please try it @hissssst.

If this is still a problem please reopen this issue.
