### ISSUE TITLE
pylddwrap uses ldd from the base system and not nix

### ISSUE THREAD

**Issue by soleera** [thiagokokada/nix-alien#76]
I'm running nix on a musl-based distro, which mean the native ldd called by pylddwrap will not work with nix-alien. We need to use the ldd provided by nix instead (`${pkgs.stdenv.cc.bintools.libc_bin}/bin/ldd`), however I'm not sure how feasible that change is given that pylddwrap has `/usr/bin/env` hard-coded into the process call...

**Comment by thiagokokada** [comment]
Does not look hugely difficult, basically we need to patch this line: https://github.com/Parquery/pylddwrap/blob/master/lddwrap/__init__.py#L196

I will open a PR in https://github.com/NixOS/nixpkgs soon-ish since I am also the maintainer of the library there.

**Comment by thiagokokada** [comment]
The change was merged upstream. Once it hits `nixpkgs-unstable` channel I will update the Flake lock so it uses it.

**Comment by thiagokokada** [comment]
Fixed in 1211a1cc3167c40949e5981bd62126399eee58a8.
