### ISSUE TITLE
Need a way to specify locally-provided libraries

### ISSUE THREAD

**Issue by soleera** [thiagokokada/nix-alien#77]
Some binaries come packaged with their own library files, however it doesn't look like there's any way to tell nix-alien not to treat these as external dependencies.

As an example, nix-ld [includes a script](https://github.com/Mic92/nix-ld/blob/3e6d944d085655fed097d20d1daacd294511b7f7/examples/zoom.nix) for the [Linux Zoom client ](https://zoom.us/client/5.4.57862.0110/zoom_x86_64.pkg.tar.xz). The client comes with its own Qt5 libraries which didn't need to be added to the nix-ld script, however nix-alien will still pick these up as external dependencies and will try to find a suitable candidate regardless.

It would be great if we had a way to provide a `PATH`-like string for `nix-alien` to check first before it begins searching for external libraries (or at least to add as another option to the list of candidates).

**Comment by thiagokokada** [comment]
One option would be for `fzf` show a `SKIP` option or something, that when selected it will not added those libraries to the environment.

WDYT @soleera ?

**Comment by thiagokokada** [comment]
> One option would be for `fzf` show a `SKIP` option or something, that when selected it will not added those libraries to the environment.

This approach would mean that the auto selection of libraries when there is only one candidate would not work anymore, but maybe this is better anyway.

**Comment by thiagokokada** [comment]
I was thinking about this feature and want to understand what is the value of it? Does Zoom does not work when loaded with the libs from `nixpkgs`? Are those simply ignored?

Because this use cases seems really niche and only usable for non-NixOS systems it looks like, while `nix-alien` generally focuses more in the NixOS use case (it works outside of it, but them generally it is easier to just use your distro package manager or something).

**Comment by thiagokokada** [comment]
Not completely related, but I just added a new `--edit` flag that allow you to quickly edit the generated Nix file if you want. This should allow the cases where you want to change something in the generated file.

**Comment by Lord-Valen** [comment]
This is useful for any case where the binary is shipped with `.so` files, especially when they are not in nixpkgs. A possible interface might be just pointing at specific files with a flag. That doesn't scale too well but it works fine for simple cases.
