### ISSUE TITLE
NIX_LD isn't a PATH-like variable

### ISSUE THREAD

**Issue by soleera** [thiagokokada/nix-alien#78]
`NIX_LD` is [executed directly](https://github.com/Mic92/nix-ld/blob/6ac25c22be4ca118e2a94f626671a52612642a9e/src/nix-ld.c#L439) by `nix-ld`, not processed as a `PATH`-like variable, so we should remove `${"\${NIX_LD:+':'}$NIX_LD"}` from [`nix_ld.template.nix`](https://github.com/thiagokokada/nix-alien/blob/936c78f734260784b8df29535e7ef83fa9563fd7/nix_alien/nix_ld.template.nix#L12) and [`nix_ld_flake.template.nix`](https://github.com/thiagokokada/nix-alien/blob/936c78f734260784b8df29535e7ef83fa9563fd7/nix_alien/nix_ld_flake.template.nix#L22) (e.g. [this](https://github.com/Mic92/nix-ld/blob/3e6d944d085655fed097d20d1daacd294511b7f7/examples/masterpdfeditor.nix#L14) is how the nix-ld example scripts set `NIX_LD` at the moment). 

Currently this results in a segmentation fault when trying to use `nix-alien-ld`.

**Comment by thiagokokada** [comment]
Pushed a fix in commit 32d5665bd85cd81e82972704e1063896c999d0b2, if you @soleera could test it would be useful since I don't use `nix-ld` anymore.

**Comment by thiagokokada** [comment]
I am assuming that the issue was fixed with the commit above, so closing this issue. If this is still an issue, please re-open.
